GET http://localhost:5050/user

#####

GET http://localhost:5050/user/get/{{id}}

#####

GET http://localhost:5050/user/get/git?email={{email}}

#####

POST http://localhost:5050/user/register
Content-Type: application/json; charset="utf-8"

{
  "id": "admin",
  "pw": "123",
  "email": "psw4888@naver.com"
}

#####

PUT http://localhost:5050/user/modify/{{id}}/{{state}}

