GET http://localhost:7070/users/state-ok

#####

GET http://localhost:7070/users/{{id}}

#####

GET http://localhost:7070/users?email={{email}}

#####

POST http://localhost:7070/users/register
Content-Type: application/json; charset="utf-8"

{
  "id": "admin",
  "pw": "123",
  "email": "psw4888@naver.com"
}

#####

PUT http://localhost:7070/users/{{id}}}/modify/states?state={{state}}

